//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _211116__doboverseny
{
    using System;
    using System.Collections.Generic;
    
    public partial class versenyzok
    {
        public int rajtszam { get; set; }
        public string nev { get; set; }
        public System.DateTime szuletes { get; set; }
        public string nem { get; set; }
        public int fk_versenyszam_id { get; set; }
        public string korosztaly { get; set; }
    
        public virtual versenyszamok versenyszamok { get; set; }
    }
}
