//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _220204_diakok_adatai
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tanulo
    {
        public int Id { get; set; }
        public string TanuloId { get; set; }
        public string Nev { get; set; }
        public System.DateTime Szuletes { get; set; }
        public string Osztaly { get; set; }
        public int Fk_Kepzes_Id { get; set; }
        public double Atlag { get; set; }
    
        public virtual Kepzes Kepzes { get; set; }
    }
}
